version: '3'
services:
  laravel:
    image: 'laravel:latest'
    ports:
      - '8000:80'
    volumes:
      - './laravel-app:/var/www/html'
    networks:
      - my_network

networks:
  my_network:

volumes:
  laravel-app:
